config/routes.rb
Rails.application.routes.draw do
  resources :jira_projects, only: [:index, :show]

  resources :employees, only: [:index, :show] do
    member do
      get 'coassignee_graph'
      get 'coassignee_graph_between'
    end
  end

  namespace :tests do
    get 'simple_graph'
  end
end

app/models/jira_project.rb
class JiraProject < ApplicationRecord

  validates :key, presence: true
  validates :name, presence: true
  
  has_many :issues, class_name: 'JiraIssue', foreign_key: 'project_id'

  has_many :assignees, -> { distinct }, through: :issues, source: :assignee
  has_many :reporters, -> { distinct }, through: :issues, source: :reporter

  '''
  Proportion of all issues opened on this project that are assigned to the given employee
  '''
  def assignee_proportion(assignee:)
    self.issues.where(assignee: assignee).count.to_f / 
    self.issues.count
  end

  '''
  Proportion of all issues opened on this project that are assigned to the given employee
  '''
  def reporter_proportion(reporter:)
    self.issues.where(reporter: reporter).count.to_f / 
    self.issues.count
  end
end

app/controllers/jira_projects_controller.rb
class JiraProjectsController < ApplicationController

  def index
    @projects = JiraProject.all
  end

  def show
    @project = JiraProject.find(params[:id])

    @assignees = @project.assignees.to_a
    @assignee_proportions = Hash[
      @assignees.map {|a| [a.id, @project.assignee_proportion(assignee: a)] }
    ]
    @assignees.sort_by! {|a| @assignee_proportions[a.id] }.reverse!

    @reporters = @project.reporters.to_a
    @reporter_proportions = Hash[
      @reporters.map {|r| [r.id, @project.reporter_proportion(reporter: r)] }
    ]
    @reporters.sort_by! {|r| @reporter_proportions[r.id] }.reverse!
  end
end

app/views/jira_projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, jira_project_path(project) %></li>
  <% end %>
</ul>

app/views/jira_projects/show.html.erb
<h1>Project - <%= @project.name %></h1>

<h2>Assignees</h2>
<table>
  <% @assignees.each do |employee| %>
    <tr>
      <td><%= link_to employee.name, employee_path(employee) %></td>
      <td><%= @assignee_proportions[employee.id].pct_string %></td>
    </tr>
  <% end %>
</table>

<h2>Reporters</h2>
<table>
  <% @reporters.each do |employee| %>
    <tr>
      <td><%= link_to employee.name, employee_path(employee) %></td>
      <td><%= @reporter_proportions[employee.id].pct_string %></td>
    </tr>
  <% end %>
</table>